### ISSUE TITLE
Create User (для всех блоков)

### ISSUE THREAD

**Issue by HappySwifter** [hackathon-almet-22/backend#3]
Создание пользователя с разными типами аккаунтов **type**

**client** Клиент
**admin** Модератор
**eventMaker** Организатор (может создавать новые мероприятия только после одобрения админом (поле **isApproved**))

**Comment by hodjaev** [comment]
![image](https://user-images.githubusercontent.com/69766846/189514761-20a52da8-bc96-40a4-b4b0-533db967249a.png)
